name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Upload Streamlit code to EC2
      uses: scottbrenner/amazon-ec2-github-runner@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        instance-id: ${{ secrets.EC2_INSTANCE_ID }}
        key-name: ${{ secrets.EC2_KEY_NAME }}
        file-path: ./streamlit.py
        remote-path: /home/ubuntu/streamlit.py

    - name: Run Streamlit on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_KEY_NAME }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install streamlit firebase selenium
        nohup streamlit run /home/ubuntu/streamlit.py --server.port 80 &
        EOF
